package problema8.network.jsonprotocol;

public enum ResponseType {
    SEND_DETAILS_FOR_ALL_CHILDREN, SEND_NUMBER_OF_EVENTS, SEND_CHILDREN, OK, ERROR, USER_LOGGED_IN, USER_LOGGED_OUT, SEND_AGE_GROUPS, SEND_EVENTS, SEND_EVENTS_BY_AGE_GROUP, SEND_CHILD_AND_ENROLLMENT, SEND_CHILDREN_BY_EVENT, CHILD_ENROLLED
}
