namespace Networking.jsonprotocol;

public enum RequestType
{
    GET_DETAILS_FOR_ALL_CHILDREN, GET_CHILDREN, LOGIN, LOGOUT, GET_AGE_GROUPS, GET_EVENTS, GET_EVENTS_BY_AGE_GROUP, SAVE_CHILD_AND_ENROLLMENT, GET_CHILDREN_BY_EVENT, GET_NUMBER_OF_EVENTS
}