plugins {
    id 'java'
}

group 'Problema8_SC'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation project(':Problema8Model')
    implementation project(':Problema8Services')
    implementation project(':Problema8Networking')
}

test {
    useJUnitPlatform()
}