USE BazaDateSGBDTema4_test
GO

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED -- permite dirty reads

BEGIN TRAN
    SELECT * FROM Antrenori
    WAITFOR DELAY '00:00:10'
    SELECT * FROM Antrenori
COMMIT TRAN
