USE BazaDateSGBDTema4_test
GO

-- THREAD 1
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
BEGIN TRANSACTION;
    UPDATE Antrenori
    SET contact = 'dirty@email.com'
    WHERE id_antrenor = 1;

    WAITFOR DELAY '00:00:07';

ROLLBACK TRANSACTION;
