USE BazaDateSGBDTema4_test
GO


SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

BEGIN TRANSACTION
    PRINT 'PRIMA CITIRE'
    SELECT * FROM Sporturi WHERE nume = 'Racheta';

    WAITFOR DELAY '00:00:10';

    PRINT 'A DOUA CITIRE'
    SELECT * FROM Sporturi WHERE nume = 'Racheta';
COMMIT TRANSACTION;
