USE BazaDateSGBDTema4_test
GO


SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;

BEGIN TRAN
    SELECT * FROM Evenimente WHERE data >= '2025-01-01';

    WAITFOR DELAY '00:00:10';

    SELECT * FROM Evenimente WHERE data >= '2025-01-01';
COMMIT TRAN;
