plugins {
    id 'java'
}

group = 'problema8.persistence'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation project (':Problema8Model')

    implementation 'org.springframework:spring-context:6.1.1'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    runtimeOnly group: 'org.xerial', name: 'sqlite-jdbc', version: '3.49.1.0'
    implementation 'org.apache.logging.log4j:log4j-core:2.24.3'
    implementation 'org.apache.logging.log4j:log4j-api:2.24.3'

}

test {
    useJUnitPlatform()
}